name: dev1

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Azure Container Registry Login 
      uses: azure/docker-login@v1 
      with:
        login-server: nurmlau.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }} 
    
    - name: Build and Push the Docker image
      run:  | 
       docker build . -t nurmlau.azurecr.io/dev1:${{ github.run_id }}
       docker push nurmlau.azurecr.io/samplewebapp:${{ github.run_id }} 
